config/routes.rb
Rails.application.routes.draw do
  resources :car_records
  resources :user_records
  resources :event_records
  resources :ports

  resources :locations do
    member do
      get :page
    end

    collection do
      get :user_index
    end
  end

  resources :connections
  devise_for :users

  scope "/admin" do
    resources :users
  end

  root 'locations#user_index'
  post 'command_handler', to: 'commands#command_handler', as: 'command_handler'
  post 'siren', to: 'commands#siren', as: 'siren'
end

app/models/event_record.rb
# Event record
class EventRecord < ActiveRecord::Base
  belongs_to :user

  validates :description, presence: true, length: { maximum: 1000 }
end

app/controllers/event_records_controller.rb
# Event records controller
class EventRecordsController < ApplicationController
  before_action :set_event_record, only: %i[show edit update destroy]
  before_action :must_be_security_or_administrator,
                except: %i[destroy update edit]
  before_action :must_be_administrator, only: %i[destroy update edit]

  def index
    @event_records = EventRecord.order(created_at: :desc)
  end

  def show; end

  def new
    @event_record = EventRecord.new
  end

  def edit; end

  def create
    data = event_record_params
    data[:user_id] = current_user.id
    @event_record = EventRecord.new(data)
    if @event_record.save
      flash[:message] = t(:event_record_was_created)
      redirect_to @event_record
    else
      flash.now[:alert] = t(:event_record_was_not_created)
      render :new
    end
  end

  def update
    data = event_record_params
    data[:user_id] = current_user.id
    if @event_record.update(data)
      flash[:message] = t(:event_record_was_updated)
      redirect_to @event_record
    else
      flash.now[:alert] = t(:event_record_was_not_updated)
      render :edit
    end
  end

  def destroy
    if @event_record.destroy
      flash[:message] = t(:event_record_was_deleted)
      redirect_to event_records_url
    else
      flash[:alert] = t(:event_record_was_not_deleted)
      redirect_to event_records_path
    end
  end

  private

  def set_event_record
    @event_record = EventRecord.find(params[:id])
  end

  def event_record_params
    params.require(:event_record).permit(:description, :date)
  end
end

app/helpers/event_records_helper.rb
module EventRecordsHelper
end

app/views/event_records/_form.html.slim
- if not @event_record.blank?
  = form_for @event_record do |f|
    - if @event_record.errors.any?
      #error_explanation
        h2 = "#{t(:you_have_errors)}: #{@event_record.errors.count}"
        ul
          - @event_record.errors.full_messages.each do |message|
            li = message
    .form-group
      = f.label :date, t(:event_record_date)
      br
      = f.datetime_select :date, default: DateTime.now, class: 'form-control'
    .form-group
      = f.label :description, t(:event_record_description)
      = f.text_area :description, class: 'form-control', rows: '9'

    = f.submit t(:confirm), class: 'btn btn-primary'

app/views/event_records/edit.html.slim
- if not @event_record.blank?
  .event_record_form_wrapper
    h3 = t(:editing_event_record)
    br
    == render 'form'
    br
    = link_to t(:show), @event_record
    = " | "
    = link_to t(:back), event_records_path

app/views/event_records/index.html.slim
= link_to new_event_record_path, class: 'btn btn-primary' do
  span.glyphicon.glyphicon-plus
  = t(:create_event_record)
br
br

.table-responsive
  table.table.table-striped.table-bordered.table-hover#order-table
    thead
      tr
        th.text-center
          = t(:event_record_date)
        th.text-center
          = t(:event_record_description)
        th.text-center
          = t(:event_record_created_by)
        - if current_user.administrator?
          th.text-center
          th.text-center
    tbody
      - @event_records.each do |e|
        tr
          td
            = link_to e.date.strftime("%H:%M:%S %d.%m.%Y"), e
          td
            = e.description
          td
            = e.user.try(:name)
          - if current_user.administrator?
            td
              = link_to t(:edit), edit_event_record_path(e)
            td
              = link_to t(:delete),
                e,
                data: { confirm: t(:delete_confirmation) },
                method: :delete
script
  |$('#order-table').dataTable({
  |        "aLengthMenu": [[25, 50, -1], [25, 50, "All"]],
  |        "iDisplayLength": 25,
  |        "order": [[0, 'desc']],
  |        "language": { "url": "#{root_url + '/assets/Russian.json'}" }
  |    }).animate({opacity: 1})

app/views/event_records/new.html.slim
.event_record_form_wrapper
  h3 = t(:new_event_record)
  br
  == render 'form'
  br
  = link_to t(:back), event_records_path

app/views/event_records/show.html.slim
- if not @event_record.blank?
  .panel.panel-default.event_record_show_size
    .panel-heading
      h3.panel-title
        b = t(:event_record)
    .panel-body
      i = t(:event_record_date)
      br
      b = @event_record.date.strftime("%H:%M:%S %d.%m.%Y")
      hr
      i = t(:event_record_description)
      br
      b = @event_record.description
      hr
      i = t(:event_record_created_by)
      br
      b = @event_record.user.try(:name)
      hr
      div.user_record_show_footer
        = link_to t(:event_records), event_records_path
        - if current_user.administrator?
          = ' | '
          = link_to t(:edit), edit_event_record_path(@event_record)