config/routes.rb
Rails.application.routes.draw do
  resources :car_records
  resources :user_records
  resources :event_records
  resources :ports

  resources :locations do
    member do
      get :page
    end

    collection do
      get :user_index
    end
  end

  resources :connections
  devise_for :users

  scope "/admin" do
    resources :users
  end

  root 'locations#user_index'
  post 'command_handler', to: 'commands#command_handler', as: 'command_handler'
  post 'siren', to: 'commands#siren', as: 'siren'
end

app/models/user_record.rb
# User record
class UserRecord < ActiveRecord::Base
  belongs_to :user

  validates :last_name, presence: true, length: { maximum: 100 }
  validates :first_name, presence: true, length: { maximum: 100 }
  validates :middle_name, presence: true, length: { maximum: 100 }
  validates :document_type, presence: true, length: { maximum: 100 }
  validates :document_number, presence: true, length: { maximum: 100 }
  validates :document_description, presence: true, length: { maximum: 1000 }
  validates :initiator, length: { maximum: 500 }
  validates :description, length: { maximum: 1000 }
end

app/controllers/user_records_controller.rb
# User records controller
class UserRecordsController < ApplicationController
  before_action :set_user_record, only: %i[show edit update destroy]
  before_action :must_be_security_or_administrator,
                except: %i[destroy update edit]
  before_action :must_be_administrator, only: %i[destroy update edit]

  def index
    @user_records = UserRecord.order(created_at: :desc)
  end

  def show; end

  def new
    @user_record = UserRecord.new
  end

  def edit; end

  def create
    data = user_record_params
    data[:user_id] = current_user.id
    @user_record = UserRecord.new(data)
    if @user_record.save
      flash[:message] = t(:user_record_was_created)
      redirect_to @user_record
    else
      flash.now[:alert] = t(:user_record_was_not_created)
      render :new
    end
  end

  def update
    data = user_record_params
    data[:user_id] = current_user.id
    if @user_record.update(data)
      flash[:message] = t(:user_record_was_updated)
      redirect_to @user_record
    else
      flash.now[:alert] = t(:user_record_was_not_updated)
      render :edit
    end
  end

  def destroy
    if @user_record.destroy
      flash[:message] = t(:user_record_was_deleted)
      redirect_to user_records_url
    else
      flash[:alert] = t(:user_record_was_not_deleted)
      redirect_to user_records_path
    end
  end

  private

  def set_user_record
    @user_record = UserRecord.find(params[:id])
  end

  def user_record_params
    params.require(:user_record).permit(
      :date, :first_name, :middle_name, :last_name, :initiator, :document_type,
      :document_number, :date_of_issue, :document_description, :description
    )
  end
end

app/helpers/user_records_helper.rb
module UserRecordsHelper
end

app/views/user_records/_form.html.slim
- if not @user_record.blank?
  = form_for @user_record do |f|
    - if @user_record.errors.any?
      #user_error_explanation
        div class='text-center'
          h2 = "#{t(:you_have_errors)}: #{@user_record.errors.count}"
        ul
          - @user_record.errors.full_messages.each do |message|
            li = message
    div class='row'
      div class='col-md-4'
        div class='well user_well'
          .form-group
            = f.label :last_name, t(:user_record_last_name)
            = f.text_field :last_name, class: "form-control"
          .form-group
            = f.label :first_name, t(:user_record_first_name)
            = f.text_field :first_name, class: "form-control"
          .form-group
            = f.label :middle_name, t(:user_record_middle_name)
            = f.text_field :middle_name, class: "form-control"
          .form-group
            = f.label :date, t(:user_record_date)
            br
            = f.datetime_select :date,
                                default: DateTime.now,
                                class: "form-control"
          .form-group
            = f.label :initiator, t(:user_record_initiator)
            = f.text_field :initiator, class: "form-control"
      div class='col-md-4'
        div class='well user_well'
          .form-group
            = f.label :document_type, t(:user_record_document_type)
            = f.text_field :document_type, class: "form-control"
          .form-group
            = f.label :document_number, t(:user_record_document_number)
            = f.text_field :document_number, class: "form-control"
          .form-group
            = f.label :date_of_issue, t(:user_record_date_of_issue)
            br
            = f.date_select :date_of_issue,
                            start_year: 1800,
                            class: "form-control"
          .form-group
            = f.label :document_description,
                      t(:user_record_document_description)
            = f.text_area :document_description,
                          class: "form-control",
                          rows: '5'
      div class='col-md-4'
        div class='well user_well'
          .form-group
            = f.label :description, t(:user_record_description)
            = f.text_area :description, class: "form-control", rows: '13'
        = f.submit t(:confirm), class: 'btn btn-primary btn-lg'

app/views/user_records/edit.html.slim
- if not @user_record.blank?
  .user_record_form_wrapper
    div class='user_record_back'
      = link_to t(:show), @user_record
      = " | "
      = link_to t(:back), user_records_path
    h3 class='user_record_title'
      = t(:editing_user_record)
    == render 'form'

app/views/user_records/index.html.slim
= link_to new_user_record_path, class: 'btn btn-primary' do
  span.glyphicon.glyphicon-plus
  = t(:create_user_record)
br
br

.table-responsive
  table.table.table-striped.table-bordered.table-hover#order-table
    thead
      tr
        th.text-center
          = t(:user_record_date)
        th.text-center
          = t(:user_record_full_name)
        th.text-center
          = t(:user_record_initiator)
        th.text-center
          = t(:user_record_created_by)
        - if current_user.administrator?
          th.text-center
          th.text-center
    tbody
      - @user_records.each do |u|
        tr
          td
            = link_to u.date.strftime("%H:%M:%S %d.%m.%Y"), u
          td
            = "#{u.last_name} #{u.first_name} #{u.middle_name}"
          td
            = u.initiator
          td
            = u.user.try(:name)
          - if current_user.administrator?
            td
              = link_to t(:edit), edit_user_record_path(u)
            td
              = link_to t(:delete),
                        u,
                        data: { confirm: t(:delete_confirmation) },
                        method: :delete
script
  |$('#order-table').dataTable({
  |        "aLengthMenu": [[25, 50, -1], [25, 50, "All"]],
  |        "iDisplayLength": 25,
  |        "order": [[0, 'desc']],
  |        "language": { "url": "#{root_url + '/assets/Russian.json'}" }
  |    }).animate({opacity: 1})

app/views/user_records/new.html.slim
.user_record_form_wrapper
  div class='user_record_back'
    = link_to t(:back), user_records_path
  h3 class='user_record_title'
    = t(:new_user_record)
  == render 'form'

app/views/user_records/show.html.slim
- if not @user_record.blank?
  .panel.panel-default.user_record_show_size
    .panel-heading
      h3.panel-title
        b = t(:user_record)
    .panel-body
      i = t(:user_record_date)
      br
      b = @user_record.date.strftime("%H:%M:%S %d.%m.%Y")
      hr
      i = t(:user_record_full_name)
      br
      b = "#{@user_record.last_name} #{@user_record.first_name} #{@user_record \
                                                                .middle_name}"
      hr
      i = t(:user_record_document_type)
      br
      b = @user_record.document_type
      hr
      i = t(:user_record_document_number)
      br
      b = @user_record.document_number
      hr
      i = t(:user_record_date_of_issue)
      br
      b = @user_record.date_of_issue.strftime("%d.%m.%Y")
      hr
      i = t(:user_record_document_description)
      br
      b = @user_record.document_description
      hr
      i = t(:user_record_initiator)
      br
      b = @user_record.initiator
      hr
      i = t(:user_record_description)
      br
      b = @user_record.description
      hr
      i = t(:user_record_created_by)
      br
      b = @user_record.user.try(:name)
      hr
      div.user_record_show_footer
        = link_to t(:user_records), user_records_path
        - if current_user.administrator?
          = ' | '
          = link_to t(:edit), edit_user_record_path(@user_record)