config/routes.rb
Rails.application.routes.draw do
  resources :car_records
  resources :user_records
  resources :event_records
  resources :ports

  resources :locations do
    member do
      get :page
    end

    collection do
      get :user_index
    end
  end

  resources :connections
  devise_for :users

  scope "/admin" do
    resources :users
  end

  root 'locations#user_index'
  post 'command_handler', to: 'commands#command_handler', as: 'command_handler'
  post 'siren', to: 'commands#siren', as: 'siren'
end

app/models/location.rb
# Location
class Location < ActiveRecord::Base
  has_many :ports

  validates :name, presence: true, length: { maximum: 250 }

  enum access: %i[security engineer administrator]
end

app/controllers/locations_controller.rb
# Locations controller
class LocationsController < ApplicationController
  before_action :set_location, only: %i[show edit update destroy page]
  before_action :must_be_administrator, except: %i[user_index page]

  def index
    @locations = Location.order(created_at: :desc)
  end

  def user_index
    # Select locations according to rights
    if current_user.administrator?
      @locations = Location.all
    elsif current_user.engineer? || current_user.security?
      @access_value = User.roles[current_user.role]
      @locations = Location.where(access: @access_value)
    else
      @locations = nil
    end

    @ports_ids = Port.where(location_id: @locations).pluck(:id) if @locations
  end

  def show; end

  def page
    return unless @location

    # Select locations according to rights
    if current_user.administrator?
      @ports = @location.ports.order(:order_index)
    elsif current_user.engineer? || current_user.security?
      @access_value = User.roles[current_user.role]
      @ports = @location.ports
                        .where(access: @access_value)
                        .order(:order_index)
    end

    @ports_ids = @ports.map(&:id)
    @accepted_ports = [Port.port_types['temperature_chart'],
                       Port.port_types['voltage_chart'],
                       Port.port_types['controller_log']]
    @ports_with_ranges = @ports.where(port_type: @accepted_ports)
                               .pluck(:id, :port_type)
  end

  def new
    @location = Location.new
  end

  def edit; end

  def create
    @location = Location.new(location_params)
    if @location.save
      flash[:message] = t(:location_was_created)
      redirect_to @location
    else
      flash.now[:alert] = t(:location_was_not_created)
      render :new
    end
  end

  def update
    if @location.update(location_params)
      flash[:message] = t(:location_was_updated)
      redirect_to @location
    else
      flash.now[:alert] = t(:location_was_not_updated)
      render :edit
    end
  end

  def destroy
    if @location.destroy
      flash[:message] = t(:location_was_deleted)
      redirect_to locations_url
    else
      flash[:alert] = t(:location_was_not_deleted)
      redirect_to locations_path
    end
  end

  private

  def set_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:name, :description, :access)
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.slim
- if not @location.blank?
  = form_for @location do |f|
    - if @location.errors.any?
      #error_explanation
        h2 = "#{t(:you_have_errors)}: #{@location.errors.count}"
        ul
          - @location.errors.full_messages.each do |message|
            li = message
    .form-group
      = f.label :name, t(:location_name)
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.label :description, t(:location_description)
      = f.text_area :description, class: 'form-control'
    .form-group
      = f.label :access, t(:location_access)
      = f.select :access, Port.accesses.keys                                   \
                              .map{ |a| [t("#{a}"), a] },
                              {},
                              { class: 'form-control' }

    = f.submit t(:confirm), class: 'btn btn-primary'

app/views/locations/_glyphicons_templates.html.slim
- if port
  - if port.door?
    div[
      class="port_picture_wrapper alert alert-danger"
      id="#{port.location_id}_#{port.id}"
      data-toggle='tooltip'
    ]
      span.glyphicon.glyphicon-log-in

  - if port.eye?
    div[
      class="port_picture_wrapper alert alert-danger"
      id="#{port.location_id}_#{port.id}"
      data-toggle='tooltip'
    ]
      span.glyphicon.glyphicon-eye-open

  - if port.siren?
    div[
      class="port_picture_wrapper alert alert-danger"
      id="#{port.location_id}_#{port.id}"
      data-toggle='tooltip'
    ]
      span.glyphicon.glyphicon-volume-up

  - if port.chart?
    div[
      class="port_picture_wrapper alert alert-danger"
      id="#{port.location_id}_#{port.id}"
      data-toggle='tooltip'
    ]
      span.glyphicon.glyphicon-blackboard

  - if port.temperature?
    div[
      class="port_picture_wrapper alert alert-danger"
      id="#{port.location_id}_#{port.id}"
      data-toggle='tooltip'
      data-html='true'
    ]
      span.glyphicon.glyphicon-dashboard

  - if port.water?
    div[
      class="port_picture_wrapper alert alert-danger"
      id="#{port.location_id}_#{port.id}"
      data-toggle='tooltip'
    ]
      span.glyphicon.glyphicon-tint

  - if port.signal?
    div[
      class="port_picture_wrapper alert alert-danger"
      id="#{port.location_id}_#{port.id}"
      data-toggle='tooltip'
      data-html='true'
      data-last-connection="#{t(:last_connection)}"
    ]
      span.glyphicon.glyphicon-signal

  - if port.fire?
    div[
      class="port_picture_wrapper alert alert-danger"
      id="#{port.location_id}_#{port.id}"
      data-toggle='tooltip'
    ]
      span.glyphicon.glyphicon-fire

  - if port.electricity?
    div[
      class="port_picture_wrapper alert alert-danger"
      id="#{port.location_id}_#{port.id}"
      data-toggle='tooltip'
    ]
      span.glyphicon.glyphicon-flash

  - if port.door_lock?
    div[
      class="port_picture_wrapper alert alert-danger"
      id="#{port.location_id}_#{port.id}"
      data-toggle='tooltip'
    ]
      span.glyphicon.glyphicon-lock

  - if port.controller_log?
    div[
      class="port_picture_wrapper alert alert-danger"
      id="#{port.location_id}_#{port.id}"
      data-toggle='tooltip'
    ]
      span.glyphicon.glyphicon-list-alt

  - if port.pressure?
    div[
      class="port_picture_wrapper alert alert-danger"
      id="#{port.location_id}_#{port.id}"
      data-toggle='tooltip'
    ]
      span.glyphicon.glyphicon-scale

  - if port.wrench?
    div[
      class="port_picture_wrapper alert alert-danger"
      id="#{port.location_id}_#{port.id}"
      data-toggle='tooltip'
    ]
      span.glyphicon.glyphicon-wrench

app/views/locations/_port_templates.html.slim
- if ports
  - ports.each do |p|
    - if p.port_type_1?
      div class="plate"
        div class="panel panel-danger"
          div class="panel-heading"
            h3 class="panel-title"
              = p.name
          div class="panel-body" id="port_#{p.id}"
            | no data
    - if p.port_type_2?
      div class="plate"
        div class="panel panel-danger"
          div class="panel-heading"
            h3 class="panel-title"
              = p.name
          div class="panel-body" id="port_#{p.id}"
            | no data
          div class="btn btn-primary port_button" id="button_#{p.id}"
            span.glyphicon.glyphicon-plus.port_button_glyphicon
            span id="button_text_#{p.id}" class="port_button_text"
              | no data
          br
          br
    - if p.temperature_chart? || p.voltage_chart?
      br
      div class="chart-plate"
        div class="panel panel-danger"
          div class="panel-heading"
            h3 class="panel-title"
              = p.name
          div class="panel-body" id="port_#{p.id}"
            | no data

    - if p.controller_log?
      div class="log-plate"
        div class="panel panel-danger"
          div class="panel-heading"
            h3 class="panel-title"
              = p.name
          div class="panel-body" id="port_#{p.id}"
            | no data


    - if p.controller_raw_data?
      div class="controller-raw-data-plate"
        div class="panel panel-danger"
          div class="panel-heading"
            h3 class="panel-title"
              = p.name
          div class="panel-body" id="port_#{p.id}"
            | no data

app/views/locations/edit.html.slim
- if not @location.blank?
  .location_form_wrapper
    h3 = t(:editing_location)
    br
    == render 'form'
    br
    = link_to t(:show), @location
    = " | "
    = link_to t(:back), locations_path

app/views/locations/index.html.slim
= link_to new_location_path, class: 'btn btn-primary' do
  span.glyphicon.glyphicon-plus
  = t(:create_location)
br
br

.table-responsive
  table.table.table-striped.table-bordered.table-hover#order-table
    thead
      tr
        th.text-center
          = t(:location_name)
        th.text-center
          = t(:location_description)
        th.text-center
          = t(:location_access)
        th
        th
    tbody
      - @locations.each do |location|
        tr
          td
            = link_to location.name, location
          td
            = location.description
          td
            = t("#{location.access}") if location.access
          td
            = link_to t(:edit), edit_location_path(location)
          td
            = link_to t(:delete),
                      location,
                      data: { confirm: t(:delete_confirmation) },
                      method: :delete
script
  |$('#order-table').dataTable({
  |        "aLengthMenu": [[25, 50, -1], [25, 50, "All"]],
  |        "iDisplayLength": 25,
  |        "order": [[0, 'desc']],
  |        "language": { "url": "#{root_url + '/assets/Russian.json'}" }
  |    }).animate({opacity: 1})

app/views/locations/new.html.slim
.location_form_wrapper
  h3 = t(:new_location)
  br
  == render 'form'
  br
  = link_to t(:back), locations_path

app/views/locations/page.html.slim
h3
  = @location.name
br
div class="wrapper_for_sensors" id="location_#{@location.id}"

  = render partial: 'port_templates', locals: { ports: @ports }

script
  | $('#location_#{@location.id}').on('click', function(e) {
  |   trigger('#{@ports_ids.to_json.html_safe}', '#{command_handler_path}', e,
  |           'page', '#{@ports_with_ranges.to_json.html_safe}');
  | });
  |
  | $(getData('#{@ports_ids.to_json.html_safe}', '#{command_handler_path}',
  |           'page', '#{@ports_with_ranges.to_json.html_safe}'));

app/views/locations/show.html.slim
- if not @location.blank?
  .panel.panel-default.location_show_size
    .panel-heading
      h3.panel-title
        b = t(:location)
    .panel-body
      dl
        dt
          = t(:location_name)
        br
        dd
          = @location.name
        br
        dt
          = t(:location_description)
        br
        dd
          = @location.description
        br
        dt
          = t(:location_access)
        br
        dd
          = t("#{@location.access}") if @location.access
        br
        = link_to t(:locations), locations_path
        = ' | '
        = link_to t(:edit), edit_location_path(@location)

app/views/locations/user_index.html.slim
- @locations.each do |l|
  div class="plate"
    div class="panel panel-info" id="location_#{l.id}"
      div class="panel-heading"
        h3 class="panel-title"
          = link_to l.name, page_location_path(l)
      div class="panel-body"
        = l.description
        hr.hr-small
        - if current_user.administrator?
          - l.ports.order(:order_index).each do |p|
            = render partial: 'glyphicons_templates', locals: { port: p }
        - else
          - l.ports.where(access: @access_value).order(:order_index).each do |p|
            = render partial: 'glyphicons_templates', locals: { port: p }

script
  | $(getData('#{@ports_ids.to_json.html_safe}', '#{command_handler_path}',
  |           'user_index', null));