config/routes.rb
Rails.application.routes.draw do
  resources :car_records
  resources :user_records
  resources :event_records
  resources :ports

  resources :locations do
    member do
      get :page
    end

    collection do
      get :user_index
    end
  end

  resources :connections
  devise_for :users

  scope "/admin" do
    resources :users
  end

  root 'locations#user_index'
  post 'command_handler', to: 'commands#command_handler', as: 'command_handler'
  post 'siren', to: 'commands#siren', as: 'siren'
end

app/models/car_record.rb
# Car Record
class CarRecord < ActiveRecord::Base
  belongs_to :user

  validates :last_name, presence: true, length: { maximum: 100 }
  validates :first_name, presence: true, length: { maximum: 100 }
  validates :middle_name, presence: true, length: { maximum: 100 }
  validates :document_type, presence: true, length: { maximum: 100 }
  validates :document_number, presence: true, length: { maximum: 100 }
  validates :document_description, presence: true, length: { maximum: 1000 }
  validates :car_number, presence: true, length: { maximum: 100 }
  validates :car_model, presence: true, length: { maximum: 300 }
  validates :cargo, length: { maximum: 10_000 }
  validates :initiator, length: { maximum: 500 }
  validates :description, length: { maximum: 1000 }
end

app/models/connection.rb
# Connection
class Connection < ActiveRecord::Base
  has_many :ports

  validates :name, presence: true, length: { maximum: 250 }
  validates :login, presence: true
  validates :password, presence: true
  validates :identifier, presence: true, uniqueness: { case_sensitive: false }
  validates :frequency, numericality: { greater_than: 0, less_than: 100_000 }
  validates :time_out, numericality: { greater_than: 0, less_than: 100_000 }
end

app/models/connection_log.rb
# Connection log
class ConnectionLog < ActiveRecord::Base
end

app/models/event_record.rb
# Event record
class EventRecord < ActiveRecord::Base
  belongs_to :user

  validates :description, presence: true, length: { maximum: 1000 }
end

app/models/location.rb
# Location
class Location < ActiveRecord::Base
  has_many :ports

  validates :name, presence: true, length: { maximum: 250 }

  enum access: %i[security engineer administrator]
end

app/models/log.rb
# Log
class Log < ActiveRecord::Base
end

app/models/port.rb
# Port model
class Port < ActiveRecord::Base
  belongs_to :location
  belongs_to :connection

  enum port_type: %w[
    reed_switch motion_sensor temperature_sensor leak_sensor switch
    arming_switch temperature_chart connection_checker smoke_sensor
    controller_log pressure_sensor controller_raw_data voltage_chart
  ]
  enum port_number: {
    in1: 1, in2: 2, in3: 3, in4: 4, in5: 5, in6: 6, in7: 7, in8: 8, in9: 9,
    in10: 10, in11: 11, in12: 12, in13: 13, in14: 14, in15: 15, in16: 16,
    output_1: 51, output_2: 52, output_3: 53, output_4: 54, output_5: 55,
    output_6: 56, output_7: 57,
    partition_1: 101, partition_2: 102, partition_3: 103, partition_4: 104
  }

  enum extra_port_number: {
    extra_in1: 1, extra_in2: 2, extra_in3: 3, extra_in4: 4, extra_in5: 5,
    extra_in6: 6, extra_in7: 7, extra_in8: 8, extra_in9: 9, extra_in10: 10,
    extra_in11: 11, extra_in12: 12, extra_in13: 13, extra_in14: 14,
    extra_in15: 15, extra_in16: 16
  }

  enum icon: %i[
    door eye siren chart temperature water signal fire electricity door_lock
    journal pressure wrench
  ]

  enum access: %i[security engineer administrator]

  enum state: %i[disabled enabled]

  validates :name, presence: true, length: { maximum: 250 }
  validates :order_index, numericality: { greater_than: -100_000,
                                          less_than: 100_000 }
  validates :before_warning, numericality: { greater_than: -1,
                                             less_than: 100_000 }
  validates :before_alert, numericality: { greater_than: -1,
                                           less_than: 100_000 }

  def port_type_1?
    %w[
      temperature_sensor reed_switch motion_sensor leak_sensor
      connection_checker smoke_sensor pressure_sensor
    ].include?(port_type)
  end

  def port_type_2?
    %w[switch arming_switch].include?(port_type)
  end
end

app/models/record.rb
# Record
class Record < ActiveRecord::Base
end

app/models/user.rb
# User
class User < ActiveRecord::Base
  enum record_type: %i[income expenditure exchange]

  enum role: %i[security engineer administrator]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable,
         :validatable # :registerable
end

app/models/user_record.rb
# User record
class UserRecord < ActiveRecord::Base
  belongs_to :user

  validates :last_name, presence: true, length: { maximum: 100 }
  validates :first_name, presence: true, length: { maximum: 100 }
  validates :middle_name, presence: true, length: { maximum: 100 }
  validates :document_type, presence: true, length: { maximum: 100 }
  validates :document_number, presence: true, length: { maximum: 100 }
  validates :document_description, presence: true, length: { maximum: 1000 }
  validates :initiator, length: { maximum: 500 }
  validates :description, length: { maximum: 1000 }
end

app/controllers/ports_controller.rb
# Controller for ports
class PortsController < ApplicationController
  before_action :set_port, only: %i[show edit update destroy]
  before_action :must_be_administrator
  def index
    @ports = Port.order(location_id: :desc)
  end

  def show; end

  def new
    @port = Port.new
  end

  def edit; end

  def create
    @port = Port.new(port_params)
    if @port.save
      flash[:message] = t(:port_was_created)
      redirect_to @port
    else
      flash.now[:alert] = t(:port_was_not_created)
      render :new
    end
  end

  def update
    if @port.update(port_params)
      flash[:message] = t(:port_was_updated)
      redirect_to @port
    else
      flash.now[:alert] = t(:port_was_not_updated)
      render :edit
    end
  end

  def destroy
    if @port.destroy
      flash[:message] = t(:port_was_deleted)
      redirect_to ports_url
    else
      flash[:alert] = t(:port_was_not_deleted)
      redirect_to ports_path
    end
  end

  private

  def set_port
    @port = Port.find(params[:id])
  end

  def port_params
    params.require(:port).permit(
      :name, :order_index, :port_type, :port_number, :extra_port_number,
      :location_id, :connection_id, :icon, :description, :access,
      :before_warning, :before_alert, :state
    )
  end
end

app/controllers/users_controller.rb
# Users controller
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :must_be_administrator

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:message] = t(:user_was_created)
      redirect_to @user
    else
      flash.now[:alert] = t(:user_was_not_created)
      render :new
    end
  end

  def update
    values = if params[:user].is_a?(Hash) &&
                params[:user][:password_confirmation].empty? &&
                params[:user][:password].empty?
               user_params_short
             else
               user_params
             end

    if @user.update(values)
      flash[:message] = t(:user_was_updated)
      redirect_to @user
    else
      flash.now[:alert] = t(:user_was_not_updated)
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:message] = t(:user_was_deleted)
      redirect_to users_path
      return
    end
    flash[:alert] = t(:user_was_not_deleted)
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :email, :name, :role, :password, :password_confirmation
    )
  end

  def user_params_short
    params.require(:user).permit(:email, :name, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_records_helper.rb
module CarRecordsHelper
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/ports_helper.rb
module PortsHelper
end

app/helpers/user_records_helper.rb
module UserRecordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html

html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    / The above 3 meta tags *must* come first in the head;
    / any other head content must come *after* these tags
    meta name="turbolinks-cache-control" content="no-cache"
    title
      = t(:brand)
    = stylesheet_link_tag 'application',
                          media: 'all',
                          'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    nav class="navbar no-rounded-corners navbar-inverse navbar-fixed-top"
      div class="container-fluid"
        div class="navbar-header"
          button[
            type="button"
            class="navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#bs-example-navbar-collapse-1"
            aria-expanded="false"
          ]
            span class="sr-only"
              | Toggle navigation
            span class="icon-bar"
            span class="icon-bar"
            span class="icon-bar"
          a class="navbar-brand" href="#"
            = t(:brand)
        div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"
          ul class="nav navbar-nav"
            - if user_signed_in?
              - if current_user.administrator?
                li class="dropdown"
                  a[
                    href="#"
                    class="dropdown-toggle"
                    data-toggle="dropdown"
                    role="button"
                    aria-haspopup="true"
                    aria-expanded="false"
                  ]
                    = t(:settings)
                    span class="caret"
                  ul class="dropdown-menu"
                    li
                      = link_to t(:connections), connections_path
                    li
                      = link_to t(:ports), ports_path
                    li
                      = link_to t(:locations), locations_path
                    li role="separator" class="divider"
                    li
                      = link_to t(:users), users_path
                li
                  = link_to t(:administrators), user_index_locations_path
              - if current_user.security? || current_user.administrator?
                li
                  = link_to t(:event_records), event_records_path
                li
                  = link_to t(:user_records), user_records_path
                li
                  = link_to t(:car_records), car_records_path
              - if current_user.engineer?
                li
                  = link_to t(:engineers), user_index_locations_path
              - if current_user.security?
                li
                  = link_to t(:securities), user_index_locations_path
          ul class="nav navbar-nav navbar-right"
            - if user_signed_in?
              li
                = link_to t(:exit), destroy_user_session_path, method: :delete
      div id="siren_state"

    div class='main-wrapper'
      div id="flash"
        - flash.each do |name, msg|
          - if name != "timedout"
            - if name == "alert"
              - ending = "danger"
            - else
              - ending = "success"
            = content_tag :div,
                          class: "alert alert-#{ending} alert-dismissable",
                          role: "alert" do
              button.close type="button" data-dismiss="alert"
                span aria-hidden="true"
                  | &times;
                span.sr-only
                  | Close
              - if msg.kind_of?(Array)
                - msg.each do |x|
                  = x
                  br
              - else
                = msg

      = yield

    footer class='main-footer'
      div class='footer-created-by'
        | Created by profy 2016

script
  | $(document).ready(function(){
  |  setTimeout(function(){
  |    $('#flash').hide();
  |  }, 5000);
  | });
  | $(document).ready(
  |   function(){
  |     siren(
  |       '#{siren_path}',
  |       '#{t(:siren_on)}',
  |       '#{audio_tag("siren.mp3", autoplay: true, loop: true)}'
  |     );
  |    }
  | );